### ISSUE TITLE
Compatibility with other dependencies

### ISSUE THREAD

**Issue by troncomputers** [andronasef/iconify_flutter#3]
```
[tronshop] flutter pub upgrade
Resolving dependencies...
Because every version of iconify_flutter depends on flutter_svg ^1.0.3 and flutter_html >=2.0.0-nullsafety.1 <3.0.0-alpha.1 depends on flutter_svg >=0.22.0 <1.0.0, iconify_flutter is incompatible with flutter_html >=2.0.0-nullsafety.1 <3.0.0-alpha.1.
So, because tronshop depends on both flutter_html ^2.2.1 and iconify_flutter ^0.0.2, version solving failed.
pub finished with exit code 1
exit code 1
```

**Comment by andronasef** [comment]
@troncomputers 
which flutter version you use ?

**Comment by troncomputers** [comment]
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.22000.556], locale pl-PL)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.1)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.65.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

**Comment by andronasef** [comment]
@troncomputers can you give me the content of pub.yml

**Comment by troncomputers** [comment]
Did you mean `pubspec.yaml`?
```yaml
name: tronshop
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.5+5

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter 
  google_fonts: ^2.1.1
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  shared_preferences: ^2.0.11
  flutter_screenutil: ^5.0.3
  badges: ^2.0.2
  flutter_native_splash: ^1.3.3
  flutter_speed_dial: ^5.0.0+1
  jwt_decoder: ^2.0.1
  carousel_slider: ^4.0.0
  flutter_html: ^2.2.1
  rotated_corner_decoration: ^2.0.0
  community_material_icon: ^5.9.55
  dio: ^4.0.4
  auto_route: ^3.2.4
  shimmer: ^2.0.0
  get_it: ^7.2.0
  flutter_riverpod: ^2.0.0-dev.4
  flutter_barcode_scanner: ^2.0.0
  syncfusion_flutter_charts: ^19.4.42
  flutter_bloc: ^8.0.1
  infinite_scroll_pagination: ^3.1.0
  flutter_simple_treeview: ^3.0.1
  local_auth: ^1.1.11
  email_validator: ^2.0.1
  iconify_flutter: ^0.0.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.7
  freezed: ^1.1.0
  json_serializable: ^6.1.3

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
```

**Comment by andronasef** [comment]
try this one and tell me if it worked

```yml
name: tronshop
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.5+5

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter 
  google_fonts: ^2.1.1
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  shared_preferences: ^2.0.11
  flutter_screenutil: ^5.0.3
  badges: ^2.0.2
  flutter_native_splash: ^1.3.3
  flutter_speed_dial: ^5.0.0+1
  jwt_decoder: ^2.0.1
  carousel_slider: ^4.0.0
  flutter_html: ^2.2.1
  rotated_corner_decoration: ^2.0.0
  community_material_icon: ^5.9.55
  dio: ^4.0.4
  auto_route: ^3.2.4
  shimmer: ^2.0.0
  get_it: ^7.2.0
  flutter_riverpod: ^2.0.0-dev.4
  flutter_barcode_scanner: ^2.0.0
  syncfusion_flutter_charts: ^19.4.42
  flutter_bloc: ^8.0.1
  infinite_scroll_pagination: ^3.1.0
  flutter_simple_treeview: ^3.0.1
  local_auth: ^1.1.11
  email_validator: ^2.0.1
  iconify_flutter: ^0.0.2

  cupertino_icons: ^1.0.2

dependency_overrides: 
  flutter_svg: 1.0.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.7
  freezed: ^1.1.0
  json_serializable: ^6.1.3

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
```
